Added k3-fragments plugin
getkirby/getkirby.com pull request #1424
Opened 2021-07-20 16:51 UTC by samzzi

2021-07-20 16:56 UTC, afbora commented
Need "genxbe/plugin-developer.txt" file

2021-07-20 17:13 UTC, samzzi commented
@afbora I got a mail/notification from you via github with the msg "Need plugin-developer.txt" (but can't find it here 😊) but that's already there from previous plugins 😬

2021-07-20 17:15 UTC, afbora commented
Yes, I realized later and delete the comment :)

2021-07-20 17:26 UTC, afbora approved these changes

2021-07-20 19:27 UTC, lukasbestle requested changes

2021-07-20 19:27 UTC, lukasbestle commented on content/plugins/genxbe/fragments/plugin.txt
> +Description: Kirby3 Fragments is a small string/translation helper. You can use fragments in your code 'laravel/blade' style and optionally translate them on site or page level. Additionaly you can p
The description is quite long for the layout on the plugins page. Suggestion for a shorter version:

```suggestion
Description: Small string/translation helper for fragments 'laravel/blade' style. Supports translating fragments (e.g. static labels) on site or page level and passing placeholders to fragments.
```

2021-07-20 19:28 UTC, lukasbestle commented
@samzzi Thank you very much for your contribution. One comment regarding the description, see above. Could you please also squash your commits for a cleaner commit history?

2021-07-22 09:34 UTC, samzzi commented
> @samzzi Thank you very much for your contribution. One comment regarding the description, see above. Could you please also squash your commits for a cleaner commit history?

👍 for the description, thanks for the suggestion! I'll have to search how I can squash commits on an open pull request, I'll fix it once I know how 😬 Thanks for the feedback though!

2021-07-22 09:35 UTC, afbora commented
Do you use any program like Github Desktop?

2021-07-22 19:27 UTC, merged

2021-07-22 19:27 UTC, lukasbestle commented
I've squash-merged the PR via the GitHub UI. :)

2021-07-23 07:32 UTC, samzzi commented
@lukasbestle cheer mate and apologies for the delay in looking into it, i'm swamped at the moment. (I used the only freetime I had to create this plugin, haha ;)) I'll take note for next time though! Thx!