qrcode plugin has a panel field now
getkirby/getkirby.com pull request #1469
Opened 2021-08-30 13:41 UTC by bnomei

2021-08-30 20:00 UTC, lukasbestle requested changes
Could you please rebase your PR against the `main` branch of getkirby.com and/or squash the commits? Otherwise we'll have a mess of all the commits in the commit history.

2021-08-30 20:00 UTC, lukasbestle commented on content/plugins/bnomei/qrcode/plugin.txt
> +Description: Generate QRCodes. The included Panel-Field will show the QRCode and trigger download on click.
```suggestion
Description: Generate QRCodes. The included Panel field will show the QRCode and trigger download on click.
```

2021-08-31 07:57 UTC, bnomei commented
that would mean i can not do this web-based but have to download the full getkirby.com repo and do git "magic". maybe some other day. just leave the pr open if you want. 

https://medium.com/gyanblog-coding-problems/git-how-to-create-a-pr-with-no-history-of-commits-96dcfa4ea532

2021-09-04 14:34 UTC, lukasbestle commented
I'm assuming you have created the PR on GitHub directly. You can avoid the commit history issue by directly editing the file in our `main` branch, which will automatically create a new PR branch for you in your own fork that is based on the latest state. If you reuse your own `master` branch over and over, the old already merged commits cause this issue, so please don't do that. :)

For this PR I'll be using GitHub's squash merge feature, which isn't optimal as your GPG signature on the original commit is lost. But for this change that's probably fine.

2021-09-04 14:34 UTC, lukasbestle approved these changes

2021-09-04 14:35 UTC, merged

2021-09-05 09:32 UTC, bnomei commented
thanks for explaining  @lukasbestle