Add cookbook recipe: Batch update content
getkirby/getkirby.com pull request #1476
Opened 2021-09-08 12:51 UTC by sebastiangreger

As this is a task that keeps popping up in the forum etc., I finally got around to write up my approach for updating large amounts of content (I've done this several times with up to 10.000 pages per run, and refined this solution slowly over time).

Written to build up gradually, from explaining the underlying logic all the way to dealing with server time-outs on large batches, I tried to keep it as barebone as possible (added in a few examples though, to illustrate how to deal with different types of content). Code snippets have been tested with a fresh Starterkit setup (Kirby 3.5).

I'm still a bit unsure should I add in more checks (for example, the current code fails if the field to update doesn't actually exist on some page in the collection looped over), which would make it more robust for copy-paste reuse, but also a tad more complex. Feedback welcome; I could add those validation checks in, no problem. Better to keep it short or add extra code that makes the experience of using the sample code more smooth?

2021-09-12 13:46 UTC, texnixe commented
Hey @sebastiangreger Great recipe! I think we can leave it as is without the additional checks but should then add a note that this is not a copy&go recipe.

Not a must, but since this comes up ever so often, it would be nice to have an example for multi-language sites. What do you think?

2021-09-13 08:57 UTC, sebastiangreger commented
Thank you for your feedback, @texnixe 

> I think we can leave it as is without the additional checks but should then add a note that this is not a copy&go recipe.

Good to hear you agree; I, too, believe it is better to keep it simple …makes it is easier to follow along. I added a note about the limitations.

> Not a must, but since this comes up ever so often, it would be nice to have an example for multi-language sites. What do you think?

Very important point that I completely forgot about; language versions absolutely have to be addressed in the recipe! I decided against adding more examples, as (if I'm not overlooking anything) it is really just about adding the language code to read/write operations. So I decided to globally switch from the `$page->myfield()` shorthand to the formally correct `$page->content()->myfield()` in all examples (also reduces potential for error if field names collide with page methods' names) and added a paragraph about adding the language code to the `content()` method as well as to the `update()` call.

I also did a few minor edits for style and fixed some typos.

Please feel free to edit the sample code if my style is not 100% somewhere or to ask for further improvements if you still see something missing :slightly_smiling_face:

2021-09-19 15:35 UTC, texnixe requested changes
I found only two small issues.

As already discussed on the forum a while ago, another option for large data sets would be to run a script on the command line. But we can move this to a future recipe which is on my list anyway and reference that later.

2021-09-19 15:35 UTC, texnixe commented on content/docs/2_cookbook/2_content/0_batch-update/cookbook-recipe.txt
> +Now our update loop can be triggered using the URL `mydomain.com/batch-update-content`. This includes a check to verify admin status; the route will fail unless logged in. It is a good idea to delete
I'd move the last sentence into a warning block

2021-09-19 15:35 UTC, texnixe commented on content/docs/2_cookbook/2_content/0_batch-update/cookbook-recipe.txt
> +Similarly, we could change other attributes of Blocks objects; for instance we could manipulate the `$old['type']` variable to make turn all blocks of type `text` into a (hypothetical) custom block t
make turn => turn or convert

2021-09-20 07:32 UTC, sebastiangreger commented
> I found only two small issues.

Thanks, I fixed the sentence and added a warning block (I don't currently have a setup to render the recipe into its final layout, so tried to be a bit cautious on using too many blocks as I can't picture how this whole thing will look like when rendered; but this indeed should be highlighted as a warning).

> As already discussed on the forum a while ago, another option for large data sets would be to run a script on the command line. But we can move this to a future recipe which is on my list anyway and reference that later.

The CLI is of course the straightforward way of doing it and pairing these two recipes sounds like a great idea to show the alternatives :+1: I altered the sentence about the need for a staggered process to mention the CLI already, as I think it is important to highlight that this is an alternative, not the only solution.

To briefly illustrate my motivation for this "workaround approach": I hoped to find a robust and reusable solution that does not require shell access (one of the great benefits of Kirby being that it can be run on the most minimal hosting packages) and avoids some headaches with PHP on shell (e.g. when the web server is configured to use a different version than the SSH user) and hence has a low barrier for entry.

2021-09-20 09:29 UTC, texnixe approved these changes

2021-09-20 09:29 UTC, merged