Cookbook Recipe: Git-based deployment with Dokku
getkirby/getkirby.com pull request #1627
Opened 2022-01-05 21:42 UTC by alancwoo

Hello! I'm submitting a cookbook recipe for deploying Kirby with git and dokku. Hope it is helpful!

2022-01-05 21:44 UTC, texnixe commented
Ah cool! I always wanted to try this out myself, with your recipe it will be easier than ever. Looking forward to reviewing it!

2022-01-08 21:04 UTC, texnixe commented on content/docs/2_cookbook/9_setup/0_git-based-deployment-with-dokku/cookbook-recipe.txt
> +git push live
For me this only worked with
```
git push --set-upstream live main
```

2022-01-08 21:07 UTC, texnixe requested changes
I created a PR with a few typo fixes over at your fork. 

Apart from that and the one comment here, everything worked fine (apart from the Let's Encrypt part which is likely due to the domain not having propagated yet).

Great recipe! I particularly like the bonus part.

2022-01-09 18:23 UTC, closed without merging

2022-01-10 17:08 UTC, alancwoo commented
Great, thanks for the fixes @texnixe - hope it's useful!